#!/usr/bin/env python
# encoding: utf-8
"""
svsim

Script for running the svsim pipeline

Created by Måns Magnusson on 2015-01-29.
Copyright (c) 2015 __TheSvestTeam__. All rights reserved.
"""

from __future__ import print_function
from __future__ import unicode_literals

import sys
import os
import click
import pkg_resources

from pprint import pprint as pp
from codecs import getwriter

from svsim.commands import (create_donor_contigs, simulate_genome, simulate_reads,
                            map_reads, pipeline)

if sys.version_info < (3,0):
    sys.stdout = getwriter('UTF-8')(sys.stdout)

version = pkg_resources.require("svsim")[0].version


def print_version(ctx, param, value):
    """Callback function for printing version and exiting
    Args:
        ctx (object) : Current context
        param (object) : Click parameter(s)
        value (boolean) : Click parameter was supplied or not
    Returns:
        None:
    """
    if not value or ctx.resilient_parsing:
        return
    click.echo('svsim version: ' + version)
    ctx.exit()


###         This is the main script         ###

@click.group()
@click.option('--version',
                is_flag=True,
                callback=print_version,
                expose_value=False,
                is_eager=True
)
def svsim():
    """
    Tool for simulating structural variations.\n
    For more information, please run:
    svsim COMMAND --help \n
        """
    pass

svsim.add_command(simulate_genome)
svsim.add_command(simulate_reads)
svsim.add_command(map_reads)
svsim.add_command(create_donor_contigs)
svsim.add_command(pipeline)

if __name__ == '__main__':
    svsim()
